=== CxsLucyfer/tools/schema_non_human.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "authors": {
            "description": "The attributed author for the library, as defined in the cdnjs package JSON file for this library.",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "object",
                "properties": {
                    "email": {
                        "anyOf": [
                            {
                                "type": "string",
                                "minLength": 1
                            },
                            {
                                "type": "null"
                            }
                        ]
                    },
                    "name": {
                        "type": "string",
                        "minLength": 1
                    },
                    "url": {
                        "anyOf": [
                            {
                                "type": "string",
                                "minLength": 1
                            },
                            {
                                "type": "null"
                            }
                        ]
                    }
                },
                "additionalProperties": false,
                "required": [
                    "name"
                ]
            }
        },
        "autoupdate": {
            "description": "Subscribes the package to an autoupdating service when a new version is released.",
            "type": "object",
            "properties": {
                "fileMap": {
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "type": "object",
                        "properties": {
                            "basePath": {
                                "type": "string"
                            },
                            "files": {
                                "type": "array",
                                "minItems": 1,
                                "uniqueItems": true,
                                "items": {
                                    "type": "string",
                                    "minLength": 1
                                }
                            }
                        },
                        "required": [
                            "basePath",
                            "files"
                        ],
                        "additionalProperties": false
                    }
                },
                "source": {
                    "type": "string",
                    "pattern": "^git|npm$"
                },
                "target": {
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "fileMap",
                "source",
                "target"
            ],
            "additionalProperties": false
        },
        "description": {
            "description": "The description of the library if it has been provided in the cdnjs package JSON file.",
            "type": "string",
            "minLength": 1
        },
        "filename": {
            "description": "This will be the name of the default file for the library.",
            "anyOf": [
                {
                    "type": "string",
                    "minLength": 1
                },
                {
                    "type": "null"
                }
            ]
        },
        "homepage": {
            "description": "A link to the homepage of the package, if one is defined in the cdnjs package JSON file. Normally, this is either the package repository or the package website.",
            "anyOf": [
                {
                    "type": "string",
                    "minLength": 1
                },
                {
                    "type": "null"
                }
            ]
        },
        "keywords": {
            "description": "An array of keywords provided in the cdnjs package JSON for the library.",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "string",
                "minLength": 1
            }
        },
        "license": {
            "description": "The license defined for the library on cdnjs, as a string. If the library has a custom license, it may not be shown here.",
            "anyOf": [
                {
                    "type": "string",
                    "pattern": "^(\\(.+ (OR|AND) .+\\)|[a-zA-Z0-9-].*)$"
                },
                {
                    "type": "null"
                }
            ]
        },
        "name": {
            "description": "This will be the full name of the library, as stored on cdnjs.",
            "type": "string",
            "pattern": "^[a-zA-Z0-9._-]+$"
        },
        "repository": {
            "description": "The repository for the library, if known, in standard repository format.",
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "pattern": "^git|hg|svn$"
                },
                "url": {
                    "type": "string",
                    "minLength": 1
                }
            },
            "required": [
                "type",
                "url"
            ],
            "additionalProperties": false
        },
        "author": {
            "anyOf": [
                {
                    "type": "string",
                    "minLength": 1
                },
                {
                    "type": "null"
                }
            ]
        },
        "version": {
            "type": "string",
            "minLength": 1
        }
    },
    "required": [
        "description",
        "keywords",
        "name",
        "version"
    ],
    "additionalProperties": false
}

=== CxsLucyfer/tools/test/checker/schema_tests/non_human_schema_tests/autoupdate/valid/missing_autoupdate.json
{
    "name": "a-happy-tyler",
    "description": "Tyler is happy. Be like Tyler.",
    "keywords": [
        "tyler",
        "happy"
    ],
    "authors": [
        {
            "name": "Tyler Caslin",
            "email": "tylercaslin47@gmail.com",
            "url": "https://github.com/tc80"
        }
    ],
    "license": "MIT",
    "repository": {
        "type": "git",
        "url": "git://github.com/tc80/a-happy-tyler.git"
    },
    "filename": "happy.js",
    "version": "v1234"
}
