=== CxsLucyfer/tools/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "authors": {
            "description": "The attributed author for the library, as defined in the cdnjs package JSON file for this library.",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string",
                        "minLength": 1
                    },
                    "name": {
                        "type": "string",
                        "minLength": 1
                    },
                    "url": {
                        "type": "string",
                        "minLength": 1
                    }
                },
                "additionalProperties": false,
                "required": [
                    "name"
                ]
            }
        },
        "autoupdate": {
            "description": "Subscribes the package to an autoupdating service when a new version is released.",
            "type": "object",
            "properties": {
                "fileMap": {
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "type": "object",
                        "properties": {
                            "basePath": {
                                "type": "string"
                            },
                            "files": {
                                "type": "array",
                                "minItems": 1,
                                "uniqueItems": true,
                                "items": {
                                    "type": "string",
                                    "minLength": 1
                                }
                            }
                        },
                        "required": [
                            "basePath",
                            "files"
                        ],
                        "additionalProperties": false
                    }
                },
                "source": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                }
            },
            "required": [
                "fileMap",
                "source",
                "target"
            ],
            "additionalProperties": false
        },
        "description": {
            "description": "The description of the library if it has been provided in the cdnjs package JSON file.",
            "type": "string"
        },
        "filename": {
            "description": "This will be the name of the default file for the library.",
            "type": "string"
        },
        "homepage": {
            "description": "A link to the homepage of the package, if one is defined in the cdnjs package JSON file. Normally, this is either the package repository or the package website.",
            "type": "string"
        },
        "keywords": {
            "description": "An array of keywords provided in the cdnjs package JSON for the library.",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        },
        "license": {
            "description": "The license defined for the library on cdnjs, as a string. If the library has a custom license, it may not be shown here.",
            "type": "string"
        },
        "name": {
            "description": "This will be the full name of the library, as stored on cdnjs.",
            "type": "string"
        },
        "repository": {
            "description": "The repository for the library, if known, in standard repository format.",
            "type": "object",
            "properties": {
                "directory": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "type",
                "url"
            ],
            "additionalProperties": false
        }
    },
    "required": [
        "autoupdate",
        "description",
        "filename",
        "keywords",
        "name"
    ],
    "additionalProperties": false
}

=== CxsLucyfer/tools/test/checker/schema_tests/human_schema_tests/license/valid/many_licenses_or.json
{
    "name": "a-happy-tyler",
    "description": "Tyler is happy. Be like Tyler.",
    "keywords": [
        "tyler",
        "happy"
    ],
    "authors": [
        {
            "name": "Tyler Caslin",
            "email": "tylercaslin47@gmail.com",
            "url": "https://github.com/tc80"
        }
    ],
    "homepage": "https://github.com/tc80",
    "license": "(MIT1 OR MIT2 OR MIT3 OR MIT4 OR MIT5)",
    "repository": {
        "type": "git",
        "url": "git://github.com/tc80/a-happy-tyler.git"
    },
    "filename": "happy.js",
    "autoupdate": {
        "source": "git",
        "target": "a-happy-tyler",
        "fileMap": [
            {
                "basePath": "src",
                "files": [
                    "*"
                ]
            }
        ]
    }
}

=== CxsLucyfer/tools/test/checker/schema_tests/(root)/valid/only_required_properties.json
{
    "name": "a-happy-tyler",
    "description": "Tyler is happy. Be like Tyler.",
    "keywords": [
        "tyler"
    ],
    "filename": "happy.js",
    "homepage": "https://github.com/tc80",
    "repository": {
        "type": "git",
        "url": "git://github.com/tc80/a-happy-tyler.git"
    },
    "autoupdate": {
        "source": "git",
        "target": "git://github.com/tc80/a-happy-tyler.git",
        "fileMap": [
            {
                "basePath": "src",
                "files": [
                    "*"
                ]
            }
        ]
    }
}

=== CxsLucyfer/tools/test/checker/schema_tests/human_schema_tests/repository/valid/type_svn.json
{
    "name": "a-happy-tyler",
    "description": "Tyler is happy. Be like Tyler.",
    "keywords": [
        "tyler",
        "happy"
    ],
    "authors": [
        {
            "name": "Tyler Caslin",
            "email": "tylercaslin47@gmail.com",
            "url": "https://github.com/tc80"
        }
    ],
    "homepage": "https://github.com/tc80",
    "license": "MIT",
    "repository": {
        "type": "svn",
        "url": "https://www.svn-is-a-valid-link.com/package/a-happy-tyler"
    },
    "filename": "happy.js",
    "autoupdate": {
        "source": "git",
        "target": "a-happy-tyler",
        "fileMap": [
            {
                "basePath": "src",
                "files": [
                    "*"
                ]
            }
        ]
    }
}

=== CxsLucyfer/tools/test/checker/schema_tests/top_level/valid/only_required_properties.json
{
    "name": "a-happy-tyler",
    "description": "Tyler is happy. Be like Tyler.",
    "keywords": [
        "tyler"
    ],
    "filename": "happy.js",
    "homepage": "https://github.com/tc80",
    "autoupdate": {
        "source": "git",
        "target": "git://github.com/tc80/a-happy-tyler.git",
        "fileMap": [
            {
                "basePath": "src",
                "files": [
                    "*"
                ]
            }
        ]
    }
}
